### PR TITLE
Remove duplicates when using alias commands

### LINKED ISSUE #310: Command aliases cause duplicates
Continuing from https://github.com/nunomaduro/laravel-console-summary/issues/9.

If I use aliases
```php
<?php
namespace App\Console\Commands;

use LaravelZero\Framework\Commands\Command;

class Projects extends Command
{
    protected $signature = 'projects';
    protected $description = 'List all running projects';

    public function __construct()
    {
        parent::__construct();
        $this->setAliases(['p']);
    }
// ...
```

I get
```
$ ./application

  Application  unreleased

  USAGE: application <command> [options] [arguments]

  projects     List all running projects
  projects     List all running projects

  app:build    Build a single file executable
  app:install  Install optional components
  app:rename   Set the application name

  make:command Create a new command
```

### PR DESCRIPTION
**Pull request by patrickdaze**
### Issue

When creating aliases for commands using `setAliases()` the `./application` currently lists duplicate commands instead of listing aliases. This would fix https://github.com/laravel-zero/laravel-zero/issues/310.

### Changes

This PR combines duplicates, and lists aliases for commands.

### Example

Command `projects` with alias `p`.

#### Current

```console
$ ./application

  Application  unreleased

  USAGE: application <command> [options] [arguments]

  projects     List all running projects
  projects     List all running projects

  app:build    Build a single file executable
  app:install  Install optional components
  app:rename   Set the application name

  make:command Create a new command
```

#### This PR

```console
$ ./application

  Application  unreleased

  USAGE: application <command> [options] [arguments]

  projects     [p] List all running projects

  app:build    Build a single file executable
  app:install  Install optional components
  app:rename   Set the application name

  make:command Create a new command
```

### Risks

This PR does not modify the list of commands used internally. It only modifies how the commands are displayed in the `USAGE` note when running `./application`. Therefore if any bugs were to be introduced by this PR, it would be limited to the `USAGE` notes of the `./application` command and not to any functionality.

When running `unique()` there's no risk of combining commands with the same name under different namespaces because `$command->getName()` includes namespaces (e.g. commands `install` and `app:install` would not be combined).

### Laravel Artisan

In comparison Laravel uses Symfony's console component for listing commands with artisan. Symfony console component displays aliases similar to this PR ([see source](https://github.com/symfony/console/blob/5.x/Descriptor/TextDescriptor.php#L221-L273)).

---

🙏 Possible to add `hacktoberfest-accepted` label to this PR? ([Details](https://hacktoberfest.digitalocean.com/details#maintainers))

### CODE REVIEW

**Comment by octoper** [comment]
@nunomaduro I've tested it! Can you merge it?  So I can close [https://github.com/laravel-zero/laravel-zero/issues/310](https://github.com/laravel-zero/laravel-zero/issues/310)

**Comment by nunomaduro** [comment]
@owenvoke Can you tag this?

**Comment by owenvoke** [comment]
Tagged and released v1.6.0 with this. 👍🏻

**Comment by patrickdaze** [comment]
🙏  Possible to add `hacktoberfest-accepted` label to this PR? [Details](https://hacktoberfest.digitalocean.com/details#maintainers)

**Comment by nunomaduro** [comment]
Done

**Pull request merged**
